#!/bin/bash

VERSION=0.0.1
ROS_VERSION="foxy"

iexec(){
            time docker container exec -it "$1" /bin/bash -l -c "source /opt/ros/${ROS_VERSION}/setup.bash && $2"
        }



if [[ "$1" == "install" ]]
then
	scripts/install.sh $2 $3 $4


elif [[ "$1" == "setup" ]]
then
	mkdir -p $PWD/src
	if [[ "$2" == "docker" ]]
	then
		platform="linux/arm64/v8,linux/amd64"
		echo "$3"
		if [[ -n "$3" ]]
		then
			echo "============ BUILDING Image ============="
			if [[ "$3" == "base" ]]
			then
				echo "============ BUILDING Base Image ============="
				image="mahesh999/opencv-realsense:0.4"
				filepath="skynet-base/"
			elif [[ "$3" == "ros" ]]
			then
				echo "============ BUILDING ROS Image ============="
				image="skynet/dev"
				filepath="skynet-ros/"
			fi
			scripts/docker-build.sh $platform $image $filepath 
		else
			echo "============ BUILDING Base Image ============="
			image="mahesha999/opencv-realsense:0.4"
			filepath="skynet-base/"
			scripts/docker-build.sh $platform $image $filepath 
			echo "============ BUILDING ROS Image ============="
			image="skynet/dev"
			filepath="skynet-ros/"
			scripts/docker-build.sh $platform $image $filepath 
		fi
		scripts/start.sh $PWD
		iexec skynet_container "ls && echo \"Starting SkyNet Container Setup\" && /ws/scripts/docker-setup.sh" 
	fi


elif [[ "$1" == "init" ]]
then
	scripts/start.sh $PWD
	iexec skynet_container "./scripts/build.sh && ./scripts/build_ros_packages.sh && cd ros_ws && source install/local_setup.bash && cd .."


elif [[ "$1" == "build" ]]
then	
	clear
	if [[ -z "$2" ]]
	then
		echo "=========== BUILDING SkyNet And Packages ==========="
		iexec skynet_container "./scripts/build.sh && ./scripts/build_ros_packages.sh && cd ros_ws && source install/local_setup.bash && cd .."
	else
		if [[  "$2" == "skynet" ]]
		then
			echo "=========== BUILDING SkyNet ==========="
			iexec skynet_container "./scripts/build.sh"
		elif [[  "$2" == "packages" ]]
		then
			echo "=========== BUILDING Packages ==========="
			iexec skynet_container "./scripts/build_ros_packages.sh && cd ros_ws && source install/local_setup.bash && cd .."
		fi
	fi

elif [[ "$1" == "cmake" ]]
then
	package="SkyNet"
	if [[ -z "$2" ]]
	then
		package="$2"
	fi
	iexec skynet_container "cd /ws/$package/build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_BUILD_TYPE=Debug -DPLATFORM=Laptop -DSLAM_MODE=orbslam2 -DINPUT_MODE=video .."


elif [[ "$1" ==  "make" ]]
then
	package="SkyNet"
	if [[ -z "$2" ]]
	then
		package="$2"
	fi
	iexec skynet_container "cd /ws/$package/build && make -j4"


elif [[  "$1" == "exec" ]]
then
	# djinn exec "cd ros_ws/src/ && ros2 pkg create --build-type ament_cmake Sensors" for creating ros2 packages
	iexec skynet_container "$2"

elif [[  "$1" == "start" ]]
then
	# djinn exec "cd ros_ws/src/ && ros2 pkg create --build-type ament_cmake Sensors" for creating ros2 packages
	if [[ "$2" == "airsim" ]]
	then
		if [[ "$3" == "AirSimNH" ]]
		then
			nohup ./envs/AirSimNH/LinuxNoEditor/AirSimNH.sh -renderoffscreen -settings=$(pwd)/envs/settings.json >> airsimnh.log &
		
		elif [[ "$3" == "LandscapeMountain" ]]
		then
			nohup ./envs/LandscapeMountains/LinuxNoEditor/LandscapeMountains.sh -renderoffscreen -settings=$(pwd)/envs/settings.json >> airsimmountain.log &
		elif [[ "$3" == "Blocks" ]]
		then
			nohup ./envs/LinuxBlocks1.8.1/LinuxNoEditor/Blocks.sh -renderoffscreen -settings=$(pwd)/envs/settings.json >> airsimblocks.log &
		fi
		sleep 5
		iexec skynet_container "cd ros_ws/ && source install/setup.bash && ros2 run airsim_lib talker"
		kill $(ps -e | grep "$3" | awk '{print $1}')
	elif [[ "$2" == "sensors" ]]
	then
		iexec skynet_container "cd ros_ws && source install/setup.bash && ros2 launch sensors sensors_launch.py"
	elif [[ "$2" == "skynet" ]]
	then
		iexec skynet_container "cd SkyNet/build && ./SkyNet"
	fi

elif [[ "$1" == "down" ]]
then
	docker stop skynet_container


elif [[ "$1" == "ps" ]]
then
	docker ps
fi
